### ISSUE TITLE
Mod caused a potential problem, but did not crash game

### ISSUE THREAD

**Issue by LoreckAvery** [jaredlll08/SlimyBoyos#2]
Here's the report:

https://paste.dimdev.org/izuburazaj.mccrash

**Comment by LoreckAvery** [comment]
Sorry if this isn't how you do these. I don't know how to read crash reports & I'm just trying to be helpful in case there is a potential bug.

**Comment by TheVisionaryOne** [comment]
I had a similar issue...

https://paste.dimdev.org/zaruweqemu.mccrash

**Comment by ghost** [comment]
@LoreckAvery @TheVisionaryOne I don't know what that website is but it looks sketchy as heck (one is marked as badware and the other is a ww1-prefixed URL???) and raises warnings on my browser.

You should use a well-established tool like https://mclo.gs/ and paste your entire `latest.log` rather than just the crash report.

**Comment by xJon** [comment]
@Brittank88 https://paste.dimdev.org used to be owned by the Dimensional Development group and the crash logs were automatically uploaded there by VanillaFix.

**Comment by jaredlll08** [comment]
Seeing as no log files exist anymore, and I haven't had many reports of this outside of the 2 given, I'm going to close this.

If anyone runs into this again, please make a new issue.
